export const CATEGORIES = [
  "Cafes & Coffee Shops",
  "Gyms & Fitness Centres",
  "Padel Courts",
  "Tennis & Squash Courts",
  "Farm Shops",
  "Garden Centres",
  "Golf Clubs",
  "Mobile Catering & Food Trucks",
  "Dessert Parlours",
  "Holiday & Caravan Parks",
  "Spa's & Health Centres",
  "Bakeries",
  "Restaurants",
];

export const UK_CITIES = [
  "Manchester",
  "London",
  "Birmingham",
  "Leeds",
  "Liverpool",
  "Edinburgh",
  "Glasgow",
  "Bristol",
  "Sheffield",
  "Bath",
  "Oxford",
  "Gloucester",
  "Northampton",
  "Leicester",
  "Coventry",
  "Cambridge",
];
